### ISSUE TITLE
What to do when solr goes down

### ISSUE THREAD

**Issue by asecondwill** [Firesphere/silverstripe-solr-search#258]
This module works great, but what do people do about Solr when it falls over?  About once a month it stops working and I have to run 

```

systemctl stop solr
systemctl start solr
```

To get the search working again.  

I can get the error to bubble up to my code:

    try {
      $result = $this->doSearch($request);

    }catch (\GuzzleHttp\Exception\ConnectException  $e) {
      die('boo');
    }

But how can I automatically restart solr?  Those commands require sudo, so I can't run them from php.

**Comment by elliot-sawyer** [comment]
It's probably best to account for the failure on your own code, rather than
relying on PHP to manage your server for you.  You end up with a more
resilient application when it's fault tolerant

**Comment by asecondwill** [comment]
A good general point.  But What would that mean in practice?  Doing the search without solr and  emailing me so i can look into what's up with solr.  The search probably wouldnt be good enough.

**Comment by michalkleiner** [comment]
Solr has a healthcheck command so you'd deal with it as with any other server service outside of PHP or Apache or PHP itself, using that and restarting the service if needed e.g. using Monit or Supervisord or any other tool you can use to manage the services.
https://solr.apache.org/guide/7_4/solr-control-script-reference.html#healthcheck (reference is for Solr 7.4 but the command is available from 4.5).

**Comment by Firesphere** [comment]
> A good general point. But What would that mean in practice? Doing the search without solr and emailing me so i can look into what's up with solr. The search probably wouldnt be good enough.

It sounds like the Solr instance you run is not having enough RAM to run full time. A possible temporary solution is to restart Solr every week or so, with a cronjob.

Second, I would strongly advice setting up error reporting in your PHP application (e.g. Sentry or Raygun), so it alerts you if an error in the application, including time-out from Solr, happens. This will help you get things back up and running again fast.

From what I understand, the problem is definitely not in the PHP side though. If Solr runs happily for a month, but then crashes, it's not the queries being sent to it that cause an issue, it's something that builds up over a certain period of time.
